### ISSUE TITLE
Does portalocker support python 3.5.2 win?

### ISSUE THREAD

**Issue by vitidev** [WoLpH/portalocker#31]
Windows 7 x64, python 3.5.2

code from example, 'somefile' exists and writeable
`file = open('somefile', 'r+')
portalocker.lock(file, portalocker.LOCK_EX)`

crashed with message
`Process finished with exit code -1073740777 (0xC0000417)`
[stack overflow/stack exhaustion]( http://stackoverflow.com/questions/20629027/process-finished-with-exit-code-1073741571)
on line 33  in portalocker.py
`msvcrt.locking(file_.fileno(), mode, -1)`

But that is not all. Rewrite code to
`portalocker.lock(file, portalocker.LOCK_SH)`
and script fail with message

File "C:\Python\lib\site-packages\portalocker\portalocker.py", line 14, in lock
    mode = msvcrt.LK_RLOCK
AttributeError: module 'msvcrt' has no attribute 'LK_RLOCK'

![mcvcrt](https://cloud.githubusercontent.com/assets/2243958/20504712/9cae9724-b051-11e6-8e17-cbbb6aae7d32.png)

**Comment by keenondrums** [comment]
+1 for Win 10

**Comment by vitidev** [comment]
+1 for python 3.6

**Comment by keenondrums** [comment]
Though it seemed like a simple AttributeError which could be fixed with simple
`getattr(msvcrt, 'LK_RLOCK', msvcrt.LK_RLCK)`
it goes deeper for me. 
Having applied the fix above I stumbled upon another issue: my python interpreter started failing.
The issue is:
(msvcrt.locking(file_.fileno(), mode, -1))[https://github.com/WoLpH/portalocker/blob/develop/portalocker/portalocker.py#L33]
If I put a random number instead of -1 it starts working.

**Comment by vitidev** [comment]
@keenondrums 
 [msvcrt.locking(fd, mode, nbytes)](https://docs.python.org/2/library/msvcrt.html) where nbytes -"the locked region of the file extends from the current file position for nbytes bytes, and may continue beyond the end of the file"
We need to lock whole file.

**Comment by keenondrums** [comment]
@vitidev I see. I just pointed that if wee need to lock the whole file -1 is not the answer.

**Comment by RazerM** [comment]
[These lines](https://github.com/WoLpH/portalocker/blob/3f8fde0c9847837db5f352e5a09604926630a035/portalocker/portalocker.py#L23-L33):

```python
savepos = file_.tell()
if savepos:
    file_.seek(0)
try:
    msvcrt.locking(file_.fileno(), mode, -1)
```

need to be replaced with something like this:

```python
savepos = file_.tell()
file_.seek(0, os.SEEK_END)
size = file_.tell()
file_.seek(0)
try:
    msvcrt.locking(file_.fileno(), mode, size)
```

I see no indication from [the documentation](https://msdn.microsoft.com/en-us/library/8054ew2f.aspx) that -1 is a valid value for the third argument. The `msvcrt.locking` causes Python to silently exit, which must be a Python bug, though.

**Comment by RazerM** [comment]
After updating 3.5.2 to 3.5.3 and still getting the crash, I verified that 2.7 and 3.4 don't cause a crash then filed a bug: http://bugs.python.org/issue29392

**Comment by TWAC** [comment]
The msvcrt module uses [_locking](https://github.com/python/cpython/blob/3.6/PC/msvcrtmodule.c#L114) which says "[It is possible to lock bytes past end of file](https://msdn.microsoft.com/en-us/library/8054ew2f.aspx#Remarks)".

Perhaps one can simply lock as much possible, 2147483647? Any larger value gives ```OverflowError: Python int too large to convert to C long```.

@techtonik added -1, what do you think?

**Comment by WoLpH** [comment]
It looks like the bug was fixed so that's good :)
http://bugs.python.org/issue29392

Still... doesn't help much with the bug though. Not sure I can help much here guys (no windows) but I'll help with anything I can offer.

**Comment by vitidev** [comment]
Second bug "AttributeError: module 'msvcrt' has no attribute 'LK_RLOCK'" not fixed in 1.1.0

**Comment by WoLpH** [comment]
Oops, Github automatically closed this. I've reopened.

**Comment by vitidev** [comment]
If fix in line 14 mode = msvcrt.LK_RLOCK -> mode = msvcrt.LK_RLCK
I did not find LK_RLOCK in any python documentation and I think it's a typo

**Comment by WoLpH** [comment]
Fixed on develop, I'm releasing a new version today :)

**Comment by WoLpH** [comment]
The new release works perfect for me on Python 2.x and 3.x on Windows, OS X and Linux
